<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExamenesRadiologicosGastroSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Exámenes Radiológicos Gastroenterológicos con cod_parent = 960
        $examenes = [
            [
                'id' => 960,
                'cod_examen' => 960,
                'cod_parent' => 960,
                'cod_dep' => null,
                'nombre_examen' => '04 04 003 | ECOGRAFÍA ABDOMINAL',
                'tipo_examen' => null,
                'habilitado' => 1,
                'sub_tipo' => 0,
                'codigo' => '04 04 003',
                'algo' => 'ECOGRAFÍA ABDOMINAL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 961,
                'cod_examen' => 961,
                'cod_parent' => 960,
                'cod_dep' => null,
                'nombre_examen' => '04 03 103 | TOMOGRAFÍA COMPUTARIZADA ANGIO DE ABDOMEN',
                'tipo_examen' => null,
                'habilitado' => 1,
                'sub_tipo' => 0,
                'codigo' => '04 03 103',
                'algo' => 'TOMOGRAFÍA COMPUTARIZADA ANGIO DE ABDOMEN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 962,
                'cod_examen' => 962,
                'cod_parent' => 960,
                'cod_dep' => null,
                'nombre_examen' => '04 03 023 | TOMOGRAFÍA COMPUTARIZADA DE COLONOSCOPÍA VIRTUAL',
                'tipo_examen' => null,
                'habilitado' => 1,
                'sub_tipo' => 0,
                'codigo' => '04 03 023',
                'algo' => 'TOMOGRAFÍA COMPUTARIZADA DE COLONOSCOPÍA VIRTUAL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 963,
                'cod_examen' => 963,
                'cod_parent' => 960,
                'cod_dep' => null,
                'nombre_examen' => '04 03 020 | TOMOGRAFÍA COMPUTARIZADA DE ABDOMEN Y PELVIS',
                'tipo_examen' => null,
                'habilitado' => 1,
                'sub_tipo' => 0,
                'codigo' => '04 03 020',
                'algo' => 'TOMOGRAFÍA COMPUTARIZADA DE ABDOMEN Y PELVIS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 964,
                'cod_examen' => 964,
                'cod_parent' => 960,
                'cod_dep' => null,
                'nombre_examen' => '04 03 014 | TOMOGRAFÍA COMPUTARIZADA DE ABDOMEN',
                'tipo_examen' => null,
                'habilitado' => 1,
                'sub_tipo' => 0,
                'codigo' => '04 03 014',
                'algo' => 'TOMOGRAFÍA COMPUTARIZADA DE ABDOMEN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 965,
                'cod_examen' => 965,
                'cod_parent' => 960,
                'cod_dep' => null,
                'nombre_examen' => '04 04 121 | ECOGRAFÍA ABDOMINAL',
                'tipo_examen' => null,
                'habilitado' => 1,
                'sub_tipo' => 0,
                'codigo' => '04 04 121',
                'algo' => 'ECOGRAFÍA ABDOMINAL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 966,
                'cod_examen' => 966,
                'cod_parent' => 960,
                'cod_dep' => null,
                'nombre_examen' => '04 04 218 | ELASTOGRAFÍA HEPÁTICA',
                'tipo_examen' => null,
                'habilitado' => 1,
                'sub_tipo' => 0,
                'codigo' => '04 04 218',
                'algo' => 'ELASTOGRAFÍA HEPÁTICA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 967,
                'cod_examen' => 967,
                'cod_parent' => 960,
                'cod_dep' => null,
                'nombre_examen' => '04 05 020 | RESONANCIA MAGNÉTICA ANGIOGRAFÍA DE ABDOMEN',
                'tipo_examen' => null,
                'habilitado' => 1,
                'sub_tipo' => 0,
                'codigo' => '04 05 020',
                'algo' => 'RESONANCIA MAGNÉTICA ANGIOGRAFÍA DE ABDOMEN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 968,
                'cod_examen' => 968,
                'cod_parent' => 960,
                'cod_dep' => null,
                'nombre_examen' => '04 05 010 | RESONANCIA MAGNÉTICA DE ABDOMEN',
                'tipo_examen' => null,
                'habilitado' => 1,
                'sub_tipo' => 0,
                'codigo' => '04 05 010',
                'algo' => 'RESONANCIA MAGNÉTICA DE ABDOMEN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 969,
                'cod_examen' => 969,
                'cod_parent' => 960,
                'cod_dep' => null,
                'nombre_examen' => '04 05 098 | COLANGIORESONANCIA',
                'tipo_examen' => null,
                'habilitado' => 1,
                'sub_tipo' => 0,
                'codigo' => '04 05 098',
                'algo' => 'COLANGIORESONANCIA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 970,
                'cod_examen' => 970,
                'cod_parent' => 960,
                'cod_dep' => null,
                'nombre_examen' => '05 01 111 | ESTUDIO MOTILIDAD ESOFÁGICA Y/O REFLUJO GASTROESOFÁGICO',
                'tipo_examen' => null,
                'habilitado' => 1,
                'sub_tipo' => 0,
                'codigo' => '05 01 111',
                'algo' => 'ESTUDIO MOTILIDAD ESOFÁGICA Y/O REFLUJO GASTROESOFÁGICO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 971,
                'cod_examen' => 971,
                'cod_parent' => 960,
                'cod_dep' => null,
                'nombre_examen' => '05 01 112 | VACIAMIENTO GÁSTRICO LÍQUIDO O SÓLIDO',
                'tipo_examen' => null,
                'habilitado' => 1,
                'sub_tipo' => 0,
                'codigo' => '05 01 112',
                'algo' => 'VACIAMIENTO GÁSTRICO LÍQUIDO O SÓLIDO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 972,
                'cod_examen' => 972,
                'cod_parent' => 960,
                'cod_dep' => null,
                'nombre_examen' => '05 01 113 | CINTIGRAFÍA VESÍCULA Y VÍA BILIAR',
                'tipo_examen' => null,
                'habilitado' => 1,
                'sub_tipo' => 0,
                'codigo' => '05 01 113',
                'algo' => 'CINTIGRAFÍA VESÍCULA Y VÍA BILIAR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 973,
                'cod_examen' => 973,
                'cod_parent' => 960,
                'cod_dep' => null,
                'nombre_examen' => '05 01 114 | DETECCIÓN DE SITIO DE SANGRAMIENTO DIGESTIVO CON GLÓBULOS ROJOS MARCADOS',
                'tipo_examen' => null,
                'habilitado' => 1,
                'sub_tipo' => 0,
                'codigo' => '05 01 114',
                'algo' => 'DETECCIÓN DE SITIO DE SANGRAMIENTO DIGESTIVO CON GLÓBULOS ROJOS MARCADOS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 974,
                'cod_examen' => 974,
                'cod_parent' => 960,
                'cod_dep' => null,
                'nombre_examen' => '05 01 115 | DETECCIÓN DIVERTÍCULO MECKEL',
                'tipo_examen' => null,
                'habilitado' => 1,
                'sub_tipo' => 0,
                'codigo' => '05 01 115',
                'algo' => 'DETECCIÓN DIVERTÍCULO MECKEL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 975,
                'cod_examen' => 975,
                'cod_parent' => 960,
                'cod_dep' => null,
                'nombre_examen' => '05 01 116 | SPECT HEPATOESPLÉNICO, EVALUACIÓN HEMANGIOMA O HIPERPLASIA',
                'tipo_examen' => null,
                'habilitado' => 1,
                'sub_tipo' => 0,
                'codigo' => '05 01 116',
                'algo' => 'SPECT HEPATOESPLÉNICO, EVALUACIÓN HEMANGIOMA O HIPERPLASIA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Verificar que no existan antes de insertar para evitar duplicados
        foreach ($examenes as $examen) {
            if (!DB::table('examenes_medicos')->where('id', $examen['id'])->exists()) {
                DB::table('examenes_medicos')->insert($examen);
            }
        }
    }
}
