<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExamenesFuncionalesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Exámenes Funcionales con cod_parent = 766
        $examenes = [
            [
                'id' => 777,
                'cod_examen' => 777,
                'cod_parent' => 766,
                'cod_dep' => null,
                'nombre_examen' => '17 07 001 | ESPIROMETRÍA BASAL',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '17 07 001',
                'algo' => 'ESPIROMETRÍA BASAL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 778,
                'cod_examen' => 778,
                'cod_parent' => 766,
                'cod_dep' => null,
                'nombre_examen' => '17 07 002 | ESPIROMETRÍA BASAL Y CON BRONCODILATADOR',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '17 07 002',
                'algo' => 'ESPIROMETRÍA BASAL Y CON BRONCODILATADOR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 779,
                'cod_examen' => 779,
                'cod_parent' => 766,
                'cod_dep' => null,
                'nombre_examen' => '17 07 003 | PRUEBA DE PROVOCACIÓN CON ALERGENO',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '17 07 003',
                'algo' => 'PRUEBA DE PROVOCACIÓN CON ALERGENO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 780,
                'cod_examen' => 780,
                'cod_parent' => 766,
                'cod_dep' => null,
                'nombre_examen' => '17 07 004 | TEST DE PROVOCACIÓN CON EJERCICIO',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '17 07 004',
                'algo' => 'TEST DE PROVOCACIÓN CON EJERCICIO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 781,
                'cod_examen' => 781,
                'cod_parent' => 766,
                'cod_dep' => null,
                'nombre_examen' => '17 07 005 | TEST DE PROVOCACIÓN CON METACOLINA',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '17 07 005',
                'algo' => 'TEST DE PROVOCACIÓN CON METACOLINA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 782,
                'cod_examen' => 782,
                'cod_parent' => 766,
                'cod_dep' => null,
                'nombre_examen' => '17 07 051 | CURVA DOSIS RESPUESTA A BRONCODILATADORES',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '17 07 051',
                'algo' => 'CURVA DOSIS RESPUESTA A BRONCODILATADORES',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 783,
                'cod_examen' => 783,
                'cod_parent' => 766,
                'cod_dep' => null,
                'nombre_examen' => '17 07 007 | ANÁLISIS DE GAS ESPIRADO',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '17 07 007',
                'algo' => 'ANÁLISIS DE GAS ESPIRADO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 784,
                'cod_examen' => 784,
                'cod_parent' => 766,
                'cod_dep' => null,
                'nombre_examen' => '17 07 008 | ESTUDIO DE CAPACIDAD DE DIFUSIÓN',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '17 07 008',
                'algo' => 'ESTUDIO DE CAPACIDAD DE DIFUSIÓN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 785,
                'cod_examen' => 785,
                'cod_parent' => 766,
                'cod_dep' => null,
                'nombre_examen' => '17 07 009 | CAPACIDAD FÍSICA DEL TRABAJO',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '17 07 009',
                'algo' => 'CAPACIDAD FÍSICA DEL TRABAJO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 786,
                'cod_examen' => 786,
                'cod_parent' => 766,
                'cod_dep' => null,
                'nombre_examen' => '17 07 010 | CURVA DE LAVADO DE NITRÓGENO',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '17 07 010',
                'algo' => 'CURVA DE LAVADO DE NITRÓGENO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 787,
                'cod_examen' => 787,
                'cod_parent' => 766,
                'cod_dep' => null,
                'nombre_examen' => '17 07 011 | CURVA DE RELACIÓN FLUJO-VOLUMEN BASAL',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '17 07 011',
                'algo' => 'CURVA DE RELACIÓN FLUJO-VOLUMEN BASAL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 788,
                'cod_examen' => 788,
                'cod_parent' => 766,
                'cod_dep' => null,
                'nombre_examen' => '17 07 012 | DISTENSIBILIDAD PULMONAR, (COMPLIANCE)',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '17 07 012',
                'algo' => 'DISTENSIBILIDAD PULMONAR, (COMPLIANCE)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 789,
                'cod_examen' => 789,
                'cod_parent' => 766,
                'cod_dep' => null,
                'nombre_examen' => '17 07 013 | MEDICIÓN DE PRESIÓN DE OCLUSIÓN',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '17 07 013',
                'algo' => 'MEDICIÓN DE PRESIÓN DE OCLUSIÓN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 790,
                'cod_examen' => 790,
                'cod_parent' => 766,
                'cod_dep' => null,
                'nombre_examen' => '17 07 014 | MEDICIÓN DE PRESIÓN INSPIRATORIA MÁXIMA',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '17 07 014',
                'algo' => 'MEDICIÓN DE PRESIÓN INSPIRATORIA MÁXIMA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 791,
                'cod_examen' => 791,
                'cod_parent' => 766,
                'cod_dep' => null,
                'nombre_examen' => '17 07 015 | MEDICIÓN DE PRESIÓN TRANS-DIAFRAGMÁTICA',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '17 07 015',
                'algo' => 'MEDICIÓN DE PRESIÓN TRANS-DIAFRAGMÁTICA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 792,
                'cod_examen' => 792,
                'cod_parent' => 766,
                'cod_dep' => null,
                'nombre_examen' => '17 07 016 | REGISTRO FLUJOMÉTRICO',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '17 07 016',
                'algo' => 'REGISTRO FLUJOMÉTRICO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 793,
                'cod_examen' => 793,
                'cod_parent' => 766,
                'cod_dep' => null,
                'nombre_examen' => '17 07 017 | RESPUESTA RESPIRATORIA AL CO2',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '17 07 017',
                'algo' => 'RESPUESTA RESPIRATORIA AL CO2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 794,
                'cod_examen' => 794,
                'cod_parent' => 766,
                'cod_dep' => null,
                'nombre_examen' => '17 07 018 | TIEMPO DE TOLERANCIA A LA FATIGA RESPIRATORIA',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '17 07 018',
                'algo' => 'TIEMPO DE TOLERANCIA A LA FATIGA RESPIRATORIA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 795,
                'cod_examen' => 795,
                'cod_parent' => 766,
                'cod_dep' => null,
                'nombre_examen' => '17 07 019 | ESTUDIO DE VENTILACIÓN ALVEOLAR VOL.ESPACIO MUERTO Y CR',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '17 07 019',
                'algo' => 'ESTUDIO DE VENTILACIÓN ALVEOLAR VOL.ESPACIO MUERTO Y CR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 796,
                'cod_examen' => 796,
                'cod_parent' => 766,
                'cod_dep' => null,
                'nombre_examen' => '17 07 025 | GASOMETRÍA ARTERIAL EN REPOSO Y EJERCICIO',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '17 07 025',
                'algo' => 'GASOMETRÍA ARTERIAL EN REPOSO Y EJERCICIO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 797,
                'cod_examen' => 797,
                'cod_parent' => 766,
                'cod_dep' => null,
                'nombre_examen' => '17 07 038 | POLIGRAFÍA CARDIORRESPIRATORIA DEL SUEÑO',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '17 07 038',
                'algo' => 'POLIGRAFÍA CARDIORRESPIRATORIA DEL SUEÑO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 798,
                'cod_examen' => 798,
                'cod_parent' => 766,
                'cod_dep' => null,
                'nombre_examen' => '17 07 052 | SATUROMETRÍA NOCTURNA DEL SUEÑO',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '17 07 052',
                'algo' => 'SATUROMETRÍA NOCTURNA DEL SUEÑO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 799,
                'cod_examen' => 799,
                'cod_parent' => 766,
                'cod_dep' => null,
                'nombre_examen' => '17 07 053 | TITULACIÓN AUTOMÁTICA DE CPAP',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '17 07 053',
                'algo' => 'TITULACIÓN AUTOMÁTICA DE CPAP',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 800,
                'cod_examen' => 800,
                'cod_parent' => 766,
                'cod_dep' => null,
                'nombre_examen' => '17 07 063 | POLIGRAFÍA CARDIORRESPIRATORIA DEL SUEÑO AMBULATORIA',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '17 07 063',
                'algo' => 'POLIGRAFÍA CARDIORRESPIRATORIA DEL SUEÑO AMBULATORIA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 801,
                'cod_examen' => 801,
                'cod_parent' => 766,
                'cod_dep' => null,
                'nombre_examen' => '17 07 054 | SATURACIÓN DE O2 EN REPOSO Y/O EJERCICIO (CON OXÍMETRO)',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '17 07 054',
                'algo' => 'SATURACIÓN DE O2 EN REPOSO Y/O EJERCICIO (CON OXÍMETRO)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 802,
                'cod_examen' => 802,
                'cod_parent' => 766,
                'cod_dep' => null,
                'nombre_examen' => '17 07 055 | SATURACIÓN DE O2 EN REPOSO Y EJERCICIO Y O2 100% (CON OXÍMETRO)',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '17 07 055',
                'algo' => 'SATURACIÓN DE O2 EN REPOSO Y EJERCICIO Y O2 100% (CON OXÍMETRO)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Verificar que no existan antes de insertar para evitar duplicados
        foreach ($examenes as $examen) {
            if (!DB::table('examenes_medicos')->where('id', $examen['id'])->exists()) {
                DB::table('examenes_medicos')->insert($examen);
            }
        }
    }
}
