<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExamenesFrecuentesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Exámenes Frecuentes (Laboratorio) con cod_parent = 804
        $examenes = [
            [
                'id' => 803,
                'cod_examen' => 803,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 01 008 | ANTITROMBINA III',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 01 008',
                'algo' => 'ANTITROMBINA III',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 804,
                'cod_examen' => 804,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 01 011 | COAGULACIÓN, TIEMPO DE',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 01 011',
                'algo' => 'COAGULACIÓN, TIEMPO DE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 805,
                'cod_examen' => 805,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 01 013 | TIEMPO DE LISIS DEL COÁGULO',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 01 013',
                'algo' => 'TIEMPO DE LISIS DEL COÁGULO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 806,
                'cod_examen' => 806,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 01 014 | PRUEBA DE ANTIGLOBULINA DIRECTA',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 01 014',
                'algo' => 'PRUEBA DE ANTIGLOBULINA DIRECTA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 807,
                'cod_examen' => 807,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 01 024 | FACTOR V',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 01 024',
                'algo' => 'FACTOR V',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 808,
                'cod_examen' => 808,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 01 025 | FACTORES VII, VIII, IX, X, XI, XII, XIII',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 01 025',
                'algo' => 'FACTORES VII, VIII, IX, X, XI, XII, XIII',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 809,
                'cod_examen' => 809,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 01 034 | CLASIFICACIÓN SANGUÍNEA AB0 Y RHD',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 01 034',
                'algo' => 'CLASIFICACIÓN SANGUÍNEA AB0 Y RHD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 810,
                'cod_examen' => 810,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 01 036 | HEMATOCRITO',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 01 036',
                'algo' => 'HEMATOCRITO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 811,
                'cod_examen' => 811,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 01 038 | HEMOGLOBINA EN SANGRE TOTAL',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 01 038',
                'algo' => 'HEMOGLOBINA EN SANGRE TOTAL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 812,
                'cod_examen' => 812,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 01 041 | HEMOGLOBINA GLICADA A1C',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 01 041',
                'algo' => 'HEMOGLOBINA GLICADA A1C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 813,
                'cod_examen' => 813,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 01 042 | HEMOGLOBINA PLASMÁTICA',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 01 042',
                'algo' => 'HEMOGLOBINA PLASMÁTICA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 814,
                'cod_examen' => 814,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 01 045 | HEMOGRAMA',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 01 045',
                'algo' => 'HEMOGRAMA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 815,
                'cod_examen' => 815,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 01 059 | TIEMPO DE PROTROMBINA',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 01 059',
                'algo' => 'TIEMPO DE PROTROMBINA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 816,
                'cod_examen' => 816,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 01 072 | TIEMPO DE SANGRÍA',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 01 072',
                'algo' => 'TIEMPO DE SANGRÍA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 817,
                'cod_examen' => 817,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 01 083 | TROMBINA, TIEMPO DE',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 01 083',
                'algo' => 'TROMBINA, TIEMPO DE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 818,
                'cod_examen' => 818,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 01 085 | TROMBOPLASTINA, TIEMPO PARCIAL DE',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 01 085',
                'algo' => 'TROMBOPLASTINA, TIEMPO PARCIAL DE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 819,
                'cod_examen' => 819,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 01 086 | VELOCIDAD DE ERITROSEDIMENTACIÓN',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 01 086',
                'algo' => 'VELOCIDAD DE ERITROSEDIMENTACIÓN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 820,
                'cod_examen' => 820,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 01 089 | FACTOR VON WILLEBRAND ANTIGÉNICO',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 01 089',
                'algo' => 'FACTOR VON WILLEBRAND ANTIGÉNICO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 821,
                'cod_examen' => 821,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 01 090 | FACTOR VON WILLEBRAND ANTIGÉNICO COFACTOR RISTOCETINA',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 01 090',
                'algo' => 'FACTOR VON WILLEBRAND ANTIGÉNICO COFACTOR RISTOCETINA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 822,
                'cod_examen' => 822,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 01 091 | PROTEÍNA C FUNCIONAL',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 01 091',
                'algo' => 'PROTEÍNA C FUNCIONAL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 823,
                'cod_examen' => 823,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 01 092 | PROTEÍNA S',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 01 092',
                'algo' => 'PROTEÍNA S',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 824,
                'cod_examen' => 824,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 01 093 | RESISTENCIA A LA PROTEÍNA C ACTIVADA',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 01 093',
                'algo' => 'RESISTENCIA A LA PROTEÍNA C ACTIVADA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 825,
                'cod_examen' => 825,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 01 114 | PROTEÍNA C ANTIGÉNICA',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 01 114',
                'algo' => 'PROTEÍNA C ANTIGÉNICA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 826,
                'cod_examen' => 826,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 01 116 | HEMOGLOBINA GLICADA, A1C, TEST',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 01 116',
                'algo' => 'HEMOGLOBINA GLICADA, A1C, TEST',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 827,
                'cod_examen' => 827,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 02 005 | ACIDO ÚRICO, EN SANGRE',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 02 005',
                'algo' => 'ACIDO ÚRICO, EN SANGRE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 828,
                'cod_examen' => 828,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 02 008 | AMILASA, EN SANGRE',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 02 008',
                'algo' => 'AMILASA, EN SANGRE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 829,
                'cod_examen' => 829,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 02 009 | AMINOÁCIDOS, CUALITATIVO EN SANGRE',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 02 009',
                'algo' => 'AMINOÁCIDOS, CUALITATIVO EN SANGRE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 830,
                'cod_examen' => 830,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 02 010 | AMONIO',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 02 010',
                'algo' => 'AMONIO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 831,
                'cod_examen' => 831,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 02 011 | BICARBONATO',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 02 011',
                'algo' => 'BICARBONATO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 832,
                'cod_examen' => 832,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 02 012 | BILIRRUBINA TOTAL',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 02 012',
                'algo' => 'BILIRRUBINA TOTAL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 833,
                'cod_examen' => 833,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 02 013 | BILIRRUBINA TOTAL Y CONJUGADA',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 02 013',
                'algo' => 'BILIRRUBINA TOTAL Y CONJUGADA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 834,
                'cod_examen' => 834,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 02 015 | CALCIO EN SANGRE',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 02 015',
                'algo' => 'CALCIO EN SANGRE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 835,
                'cod_examen' => 835,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 02 020 | COBRE EN SANGRE',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 02 020',
                'algo' => 'COBRE EN SANGRE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 836,
                'cod_examen' => 836,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 02 067 | COLESTEROL TOTAL',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 02 067',
                'algo' => 'COLESTEROL TOTAL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 837,
                'cod_examen' => 837,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 02 068 | COLESTEROL HDL',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 02 068',
                'algo' => 'COLESTEROL HDL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 838,
                'cod_examen' => 838,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 02 021 | COLINESTERASA EN SUERO O PLASMA',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 02 021',
                'algo' => 'COLINESTERASA EN SUERO O PLASMA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 839,
                'cod_examen' => 839,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 02 023 | CREATININA EN SANGRE',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 02 023',
                'algo' => 'CREATININA EN SANGRE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 840,
                'cod_examen' => 840,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 02 024 | CLEARANCE DE CREATININA',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 02 024',
                'algo' => 'CLEARANCE DE CREATININA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 841,
                'cod_examen' => 841,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 02 025 | CREATINQUINASA CK - MB ACTIVIDAD 5',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 02 025',
                'algo' => 'CREATINQUINASA CK - MB ACTIVIDAD 5',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 842,
                'cod_examen' => 842,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 02 026 | CREATINQUINASA CK - TOTAL',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 02 026',
                'algo' => 'CREATINQUINASA CK - TOTAL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 843,
                'cod_examen' => 843,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 02 034 | PERFIL LIPÍDICO',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 02 034',
                'algo' => 'PERFIL LIPÍDICO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 844,
                'cod_examen' => 844,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 02 045 | GAMMA GLUTAMILTRANSPEPTIDASA (GGT)',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 02 045',
                'algo' => 'GAMMA GLUTAMILTRANSPEPTIDASA (GGT)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 845,
                'cod_examen' => 845,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 02 046 | GASES Y EQUILIBRIO ÁCIDO BASE EN SANGRE',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 02 046',
                'algo' => 'GASES Y EQUILIBRIO ÁCIDO BASE EN SANGRE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 846,
                'cod_examen' => 846,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 02 047 | GLUCOSA EN SANGRE',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 02 047',
                'algo' => 'GLUCOSA EN SANGRE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 847,
                'cod_examen' => 847,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 02 048 | GLUCOSA, PRUEBA DE TOLERANCIA A',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 02 048',
                'algo' => 'GLUCOSA, PRUEBA DE TOLERANCIA A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 848,
                'cod_examen' => 848,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 02 075 | PERFIL BIOQUÍMICO',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 02 075',
                'algo' => 'PERFIL BIOQUÍMICO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 849,
                'cod_examen' => 849,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 02 061 | ELECTROFORESIS DE PROTEÍNAS',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 02 061',
                'algo' => 'ELECTROFORESIS DE PROTEÍNAS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 850,
                'cod_examen' => 850,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 02 076 | PERFIL HEPÁTICO',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 02 076',
                'algo' => 'PERFIL HEPÁTICO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 851,
                'cod_examen' => 851,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 02 063 | TRANSAMINASAS, OXALACÉTICA (GOT/AST), PIRÚVICA (GPT/ALT)',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 02 063',
                'algo' => 'TRANSAMINASAS, OXALACÉTICA (GOT/AST), PIRÚVICA (GPT/ALT)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 852,
                'cod_examen' => 852,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 02 064 | TRIGLICÉRIDOS EN SANGRE',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 02 064',
                'algo' => 'TRIGLICÉRIDOS EN SANGRE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 853,
                'cod_examen' => 853,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 02 066 | XILOSA, PRUEBA DE ABSORCIÓN',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 02 066',
                'algo' => 'XILOSA, PRUEBA DE ABSORCIÓN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 854,
                'cod_examen' => 854,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 02 077 | VITAMINA B12',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 02 077',
                'algo' => 'VITAMINA B12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 855,
                'cod_examen' => 855,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 02 078 | 25 OH VITAMINA D TOTAL',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 02 078',
                'algo' => '25 OH VITAMINA D TOTAL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 856,
                'cod_examen' => 856,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 02 100 | PROTEÍNAS TOTALES EN SANGRE',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 02 100',
                'algo' => 'PROTEÍNAS TOTALES EN SANGRE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 857,
                'cod_examen' => 857,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 02 101 | ALBÚMINAS EN SANGRE',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 02 101',
                'algo' => 'ALBÚMINAS EN SANGRE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 858,
                'cod_examen' => 858,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 03 004 | ANGIOTENSINA',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 03 004',
                'algo' => 'ANGIOTENSINA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 859,
                'cod_examen' => 859,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 03 006 | CORTISOL',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 03 006',
                'algo' => 'CORTISOL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 860,
                'cod_examen' => 860,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 03 012 | GASTRINA',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 03 012',
                'algo' => 'GASTRINA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 861,
                'cod_examen' => 861,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 03 014 | GONADOTROFINA CORIÓNICA, SUB-UNIDAD BETA',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 03 014',
                'algo' => 'GONADOTROFINA CORIÓNICA, SUB-UNIDAD BETA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 862,
                'cod_examen' => 862,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 03 017 | INSULINA',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 03 017',
                'algo' => 'INSULINA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 863,
                'cod_examen' => 863,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 03 031 | INSULINA, CURVA',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 03 031',
                'algo' => 'INSULINA, CURVA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 864,
                'cod_examen' => 864,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 03 019 | PROGESTERONA',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 03 019',
                'algo' => 'PROGESTERONA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 865,
                'cod_examen' => 865,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 03 020 | PROLACTINA',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 03 020',
                'algo' => 'PROLACTINA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 866,
                'cod_examen' => 866,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 03 021 | RENINA',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 03 021',
                'algo' => 'RENINA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 867,
                'cod_examen' => 867,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 03 046 | SHBG (SEX-HORMONE BINDING GLOBULIN)',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 03 046',
                'algo' => 'SHBG (SEX-HORMONE BINDING GLOBULIN)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 868,
                'cod_examen' => 868,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 03 022 | TESTOSTERONA EN SANGRE',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 03 022',
                'algo' => 'TESTOSTERONA EN SANGRE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 869,
                'cod_examen' => 869,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 03 023 | TESTOSTERONA LIBRE EN SANGRE',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 03 023',
                'algo' => 'TESTOSTERONA LIBRE EN SANGRE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 870,
                'cod_examen' => 870,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 03 123 | ÍNDICE ANDROGÉNICO (INCLUYE TESTOSTERONA TOTAL Y SHBG)',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 03 123',
                'algo' => 'ÍNDICE ANDROGÉNICO (INCLUYE TESTOSTERONA TOTAL Y SHBG)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 871,
                'cod_examen' => 871,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 03 024 | TIROESTIMULANTE (TSH)',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 03 024',
                'algo' => 'TIROESTIMULANTE (TSH)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 872,
                'cod_examen' => 872,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 03 025 | TIROGLOBULINA',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 03 025',
                'algo' => 'TIROGLOBULINA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 873,
                'cod_examen' => 873,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 03 026 | TIROXINA LIBRE (T4L)',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 03 026',
                'algo' => 'TIROXINA LIBRE (T4L)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 874,
                'cod_examen' => 874,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 03 027 | TIROXINA O TETRAYODOTIRONINA (T4)',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 03 027',
                'algo' => 'TIROXINA O TETRAYODOTIRONINA (T4)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 875,
                'cod_examen' => 875,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 03 028 | TRIYODOTIRONINA (T3)',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 03 028',
                'algo' => 'TRIYODOTIRONINA (T3)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 876,
                'cod_examen' => 876,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 03 029 | 17 - HIDROXIPROGESTERONA',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 03 029',
                'algo' => '17 - HIDROXIPROGESTERONA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 877,
                'cod_examen' => 877,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 03 030 | ESTRADIOL (17-BETA)',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 03 030',
                'algo' => 'ESTRADIOL (17-BETA)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 878,
                'cod_examen' => 878,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 03 049 | CATECOLAMINAS EN SANGRE',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 03 049',
                'algo' => 'CATECOLAMINAS EN SANGRE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 879,
                'cod_examen' => 879,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 05 008 | ANTIESTREPTOLISINA O',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 05 008',
                'algo' => 'ANTIESTREPTOLISINA O',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 880,
                'cod_examen' => 880,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 05 009 | ANTÍGENO CARCINOEMBRIONARIO (CEA)',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 05 009',
                'algo' => 'ANTÍGENO CARCINOEMBRIONARIO (CEA)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 881,
                'cod_examen' => 881,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 05 070 | ANTÍGENO PROSTÁTICO ESPECÍFICO',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 05 070',
                'algo' => 'ANTÍGENO PROSTÁTICO ESPECÍFICO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 882,
                'cod_examen' => 882,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 05 170 | ANTÍGENO CA 125, CA 15-3 Y CA 19-9',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 05 170',
                'algo' => 'ANTÍGENO CA 125, CA 15-3 Y CA 19-9',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 883,
                'cod_examen' => 883,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 05 010 | BETA-2-MICROGLOBULINA',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 05 010',
                'algo' => 'BETA-2-MICROGLOBULINA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 884,
                'cod_examen' => 884,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 05 012 | COMPLEMENTO C1Q, C2, C3, C4',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 05 012',
                'algo' => 'COMPLEMENTO C1Q, C2, C3, C4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 885,
                'cod_examen' => 885,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 06 001 | BACILOSCOPÍA POR MÉTODO DE CONCENTRACIÓN',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 06 001',
                'algo' => 'BACILOSCOPÍA POR MÉTODO DE CONCENTRACIÓN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 886,
                'cod_examen' => 886,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 06 007 | COPROCULTIVO',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 06 007',
                'algo' => 'COPROCULTIVO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 887,
                'cod_examen' => 887,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 06 008 | CULTIVO CORRIENTE',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 06 008',
                'algo' => 'CULTIVO CORRIENTE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 888,
                'cod_examen' => 888,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 06 011 | UROCULTIVO, RECUENTO DE COLONIAS Y ANTIBIOGRAMA',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 06 011',
                'algo' => 'UROCULTIVO, RECUENTO DE COLONIAS Y ANTIBIOGRAMA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 889,
                'cod_examen' => 889,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 06 025 | ANTIBIOGRAMA BACILO DE KOCH',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 06 025',
                'algo' => 'ANTIBIOGRAMA BACILO DE KOCH',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 890,
                'cod_examen' => 890,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 06 026 | ANTIBIOGRAMA CORRIENTE',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 06 026',
                'algo' => 'ANTIBIOGRAMA CORRIENTE',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 891,
                'cod_examen' => 891,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 06 027 | ANTIBIOGRAMA DE ESTUDIO DE SENSIBILIDAD POR DILUCIÓN',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 06 027',
                'algo' => 'ANTIBIOGRAMA DE ESTUDIO DE SENSIBILIDAD POR DILUCIÓN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 892,
                'cod_examen' => 892,
                'cod_parent' => 804,
                'cod_dep' => null,
                'nombre_examen' => '03 06 028 | ANTIFUNGIGRAMA (MÍNIMO 4 FÁRMACOS ANTIHONGOS)',
                'tipo_examen' => null,
                'habilitado' => null,
                'sub_tipo' => 0,
                'codigo' => '03 06 028',
                'algo' => 'ANTIFUNGIGRAMA (MÍNIMO 4 FÁRMACOS ANTIHONGOS)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Verificar que no existan antes de insertar para evitar duplicados
        foreach ($examenes as $examen) {
            if (!DB::table('examenes_medicos')->where('id', $examen['id'])->exists()) {
                DB::table('examenes_medicos')->insert($examen);
            }
        }
    }
}
