UPDATE regiones SET nombre= 'Arica y Parinacota',sigla='XV' WHERE id = 1;
UPDATE regiones SET nombre= 'Tarapacá',sigla='I' WHERE id = 2;
UPDATE regiones SET nombre= 'Antofagasta',sigla='II' WHERE id = 3;
UPDATE regiones SET nombre= 'Atacama',sigla='III' WHERE id = 4;
UPDATE regiones SET nombre= 'Coquimbo',sigla='IV' WHERE id = 5;
UPDATE regiones SET nombre= 'Valparaiso',sigla='V' WHERE id = 6;
UPDATE regiones SET nombre= 'Metropolitana de Santiago',sigla='RM' WHERE id = 7;
UPDATE regiones SET nombre= 'Libertador General Bernardo O\'Higgins',sigla='VI' WHERE id = 8;
UPDATE regiones SET nombre= 'Maule',sigla='VII' WHERE id = 9;
UPDATE regiones SET nombre= 'Ñuble',sigla='XVI' WHERE id = 10;
UPDATE regiones SET nombre= 'Biobío',sigla='VIII' WHERE id = 11;
UPDATE regiones SET nombre= 'La Araucanía',sigla='IX' WHERE id = 12;
UPDATE regiones SET nombre= 'Los Ríos',sigla='XIV' WHERE id = 13;
UPDATE regiones SET nombre= 'Los Lagos',sigla='X' WHERE id = 14;
UPDATE regiones SET nombre= 'Aisén del General Carlos Ibáñez del Campo',sigla='XI' WHERE id = 15;
UPDATE regiones SET nombre= 'Magallanes y de la Antártica Chilena',sigla='XII' WHERE id = 16;


UPDATE `ciudades` SET `nombre` = 'Arica', id_region='1' WHERE `ciudades`.`id` = 1;
UPDATE `ciudades` SET `nombre` = 'Camarones', id_region='1' WHERE `ciudades`.`id` = 2;
UPDATE `ciudades` SET `nombre` = 'General Lagos', id_region='1' WHERE `ciudades`.`id` = 3;
UPDATE `ciudades` SET `nombre` = 'Putre', id_region='1' WHERE `ciudades`.`id` = 4;
UPDATE `ciudades` SET `nombre` = 'Alto Hospicio', id_region='2' WHERE `ciudades`.`id` = 5;
UPDATE `ciudades` SET `nombre` = 'Iquique', id_region='2' WHERE `ciudades`.`id` = 6;
UPDATE `ciudades` SET `nombre` = 'Camiña', id_region='2' WHERE `ciudades`.`id` = 7;
UPDATE `ciudades` SET `nombre` = 'Colchane', id_region='2' WHERE `ciudades`.`id` = 8;
UPDATE `ciudades` SET `nombre` = 'Huara', id_region='2' WHERE `ciudades`.`id` = 9;
UPDATE `ciudades` SET `nombre` = 'Pica', id_region='2' WHERE `ciudades`.`id` = 10;
UPDATE `ciudades` SET `nombre` = 'Pozo Almonte', id_region='2' WHERE `ciudades`.`id` = 11;
UPDATE `ciudades` SET `nombre` = 'Antofagasta', id_region='3' WHERE `ciudades`.`id` = 12;
UPDATE `ciudades` SET `nombre` = 'Mejillones', id_region='3' WHERE `ciudades`.`id` = 13;
UPDATE `ciudades` SET `nombre` = 'Sierra Gorda', id_region='3' WHERE `ciudades`.`id` = 14;
UPDATE `ciudades` SET `nombre` = 'Taltal', id_region='3' WHERE `ciudades`.`id` = 15;
UPDATE `ciudades` SET `nombre` = 'Calama', id_region='3' WHERE `ciudades`.`id` = 16;
UPDATE `ciudades` SET `nombre` = 'Ollague', id_region='3' WHERE `ciudades`.`id` = 17;
UPDATE `ciudades` SET `nombre` = 'San Pedro de Atacama', id_region='3' WHERE `ciudades`.`id` = 18;
UPDATE `ciudades` SET `nombre` = 'María Elena', id_region='3' WHERE `ciudades`.`id` = 19;
UPDATE `ciudades` SET `nombre` = 'Tocopilla', id_region='3' WHERE `ciudades`.`id` = 20;
UPDATE `ciudades` SET `nombre` = 'Chañaral', id_region='4' WHERE `ciudades`.`id` = 21;
UPDATE `ciudades` SET `nombre` = 'Diego de Almagro', id_region='4' WHERE `ciudades`.`id` = 22;
UPDATE `ciudades` SET `nombre` = 'Caldera', id_region='4' WHERE `ciudades`.`id` = 23;
UPDATE `ciudades` SET `nombre` = 'Copiapó', id_region='4' WHERE `ciudades`.`id` = 24;
UPDATE `ciudades` SET `nombre` = 'Tierra Amarilla', id_region='4' WHERE `ciudades`.`id` = 25;
UPDATE `ciudades` SET `nombre` = 'Alto del Carmen', id_region='4' WHERE `ciudades`.`id` = 26;
UPDATE `ciudades` SET `nombre` = 'Freirina', id_region='4' WHERE `ciudades`.`id` = 27;
UPDATE `ciudades` SET `nombre` = 'Huasco', id_region='4' WHERE `ciudades`.`id` = 28;
UPDATE `ciudades` SET `nombre` = 'Vallenar', id_region='4' WHERE `ciudades`.`id` = 29;
UPDATE `ciudades` SET `nombre` = 'Canela', id_region='5' WHERE `ciudades`.`id` = 30;
UPDATE `ciudades` SET `nombre` = 'Illapel', id_region='5' WHERE `ciudades`.`id` = 31;
UPDATE `ciudades` SET `nombre` = 'Los Vilos', id_region='5' WHERE `ciudades`.`id` = 32;
UPDATE `ciudades` SET `nombre` = 'Salamanca', id_region='5' WHERE `ciudades`.`id` = 33;
UPDATE `ciudades` SET `nombre` = 'Andacollo', id_region='5' WHERE `ciudades`.`id` = 34;
UPDATE `ciudades` SET `nombre` = 'Coquimbo', id_region='5' WHERE `ciudades`.`id` = 35;
UPDATE `ciudades` SET `nombre` = 'La Higuera', id_region='5' WHERE `ciudades`.`id` = 36;
UPDATE `ciudades` SET `nombre` = 'La Serena', id_region='5' WHERE `ciudades`.`id` = 37;
UPDATE `ciudades` SET `nombre` = 'Paihuaco', id_region='5' WHERE `ciudades`.`id` = 38;
UPDATE `ciudades` SET `nombre` = 'Vicuña', id_region='5' WHERE `ciudades`.`id` = 39;
UPDATE `ciudades` SET `nombre` = 'Combarbalá', id_region='5' WHERE `ciudades`.`id` = 40;
UPDATE `ciudades` SET `nombre` = 'Monte Patria', id_region='5' WHERE `ciudades`.`id` = 41;
UPDATE `ciudades` SET `nombre` = 'Ovalle', id_region='5' WHERE `ciudades`.`id` = 42;
UPDATE `ciudades` SET `nombre` = 'Punitaqui', id_region='5' WHERE `ciudades`.`id` = 43;
UPDATE `ciudades` SET `nombre` = 'Río Hurtado', id_region='5' WHERE `ciudades`.`id` = 44;
UPDATE `ciudades` SET `nombre` = 'Isla de Pascua', id_region='6' WHERE `ciudades`.`id` = 45;
UPDATE `ciudades` SET `nombre` = 'Calle Larga', id_region='6' WHERE `ciudades`.`id` = 46;
UPDATE `ciudades` SET `nombre` = 'Los Andes', id_region='6' WHERE `ciudades`.`id` = 47;
UPDATE `ciudades` SET `nombre` = 'Rinconada', id_region='6' WHERE `ciudades`.`id` = 48;
UPDATE `ciudades` SET `nombre` = 'San Esteban', id_region='6' WHERE `ciudades`.`id` = 49;
UPDATE `ciudades` SET `nombre` = 'La Ligua', id_region='6' WHERE `ciudades`.`id` = 50;
UPDATE `ciudades` SET `nombre` = 'Papudo', id_region='6' WHERE `ciudades`.`id` = 51;
UPDATE `ciudades` SET `nombre` = 'Petorca', id_region='6' WHERE `ciudades`.`id` = 52;
UPDATE `ciudades` SET `nombre` = 'Zapallar', id_region='6' WHERE `ciudades`.`id` = 53;
UPDATE `ciudades` SET `nombre` = 'Hijuelas', id_region='6' WHERE `ciudades`.`id` = 54;
UPDATE `ciudades` SET `nombre` = 'La Calera', id_region='6' WHERE `ciudades`.`id` = 55;
UPDATE `ciudades` SET `nombre` = 'La Cruz', id_region='6' WHERE `ciudades`.`id` = 56;
UPDATE `ciudades` SET `nombre` = 'Limache', id_region='6' WHERE `ciudades`.`id` = 57;
UPDATE `ciudades` SET `nombre` = 'Nogales', id_region='6' WHERE `ciudades`.`id` = 58;
UPDATE `ciudades` SET `nombre` = 'Olmué', id_region='6' WHERE `ciudades`.`id` = 59;
UPDATE `ciudades` SET `nombre` = 'Quillota', id_region='6' WHERE `ciudades`.`id` = 60;
UPDATE `ciudades` SET `nombre` = 'Algarrobo', id_region='6' WHERE `ciudades`.`id` = 61;
UPDATE `ciudades` SET `nombre` = 'Cartagena', id_region='6' WHERE `ciudades`.`id` = 62;
UPDATE `ciudades` SET `nombre` = 'El Quisco', id_region='6' WHERE `ciudades`.`id` = 63;
UPDATE `ciudades` SET `nombre` = 'El Tabo', id_region='6' WHERE `ciudades`.`id` = 64;
UPDATE `ciudades` SET `nombre` = 'San Antonio', id_region='6' WHERE `ciudades`.`id` = 65;
UPDATE `ciudades` SET `nombre` = 'Santo Domingo', id_region='6' WHERE `ciudades`.`id` = 66;
UPDATE `ciudades` SET `nombre` = 'Catemu', id_region='6' WHERE `ciudades`.`id` = 67;
UPDATE `ciudades` SET `nombre` = 'Llaillay', id_region='6' WHERE `ciudades`.`id` = 68;
UPDATE `ciudades` SET `nombre` = 'Panquehue', id_region='6' WHERE `ciudades`.`id` = 69;
UPDATE `ciudades` SET `nombre` = 'Putaendo', id_region='6' WHERE `ciudades`.`id` = 70;
UPDATE `ciudades` SET `nombre` = 'San Felipe', id_region='6' WHERE `ciudades`.`id` = 71;
UPDATE `ciudades` SET `nombre` = 'Santa María', id_region='6' WHERE `ciudades`.`id` = 72;
UPDATE `ciudades` SET `nombre` = 'Casablanca', id_region='6' WHERE `ciudades`.`id` = 73;
UPDATE `ciudades` SET `nombre` = 'Concón', id_region='6' WHERE `ciudades`.`id` = 74;
UPDATE `ciudades` SET `nombre` = 'Juan Fernández', id_region='6' WHERE `ciudades`.`id` = 75;
UPDATE `ciudades` SET `nombre` = 'Puchuncaví', id_region='6' WHERE `ciudades`.`id` = 76;
UPDATE `ciudades` SET `nombre` = 'Quilpué', id_region='6' WHERE `ciudades`.`id` = 77;
UPDATE `ciudades` SET `nombre` = 'Quintero', id_region='6' WHERE `ciudades`.`id` = 78;
UPDATE `ciudades` SET `nombre` = 'Valparaíso', id_region='6' WHERE `ciudades`.`id` = 79;
UPDATE `ciudades` SET `nombre` = 'Villa Alemana', id_region='6' WHERE `ciudades`.`id` = 80;
UPDATE `ciudades` SET `nombre` = 'Viña del Mar', id_region='6' WHERE `ciudades`.`id` = 81;
UPDATE `ciudades` SET `nombre` = 'Colina', id_region='7' WHERE `ciudades`.`id` = 82;
UPDATE `ciudades` SET `nombre` = 'Lampa', id_region='7' WHERE `ciudades`.`id` = 83;
UPDATE `ciudades` SET `nombre` = 'Tiltil', id_region='7' WHERE `ciudades`.`id` = 84;
UPDATE `ciudades` SET `nombre` = 'Pirque', id_region='7' WHERE `ciudades`.`id` = 85;
UPDATE `ciudades` SET `nombre` = 'Puente Alto', id_region='7' WHERE `ciudades`.`id` = 86;
UPDATE `ciudades` SET `nombre` = 'San José de Maipo', id_region='7' WHERE `ciudades`.`id` = 87;
UPDATE `ciudades` SET `nombre` = 'Buin', id_region='7' WHERE `ciudades`.`id` = 88;
UPDATE `ciudades` SET `nombre` = 'Calera de Tango', id_region='7' WHERE `ciudades`.`id` = 89;
UPDATE `ciudades` SET `nombre` = 'Paine', id_region='7' WHERE `ciudades`.`id` = 90;
UPDATE `ciudades` SET `nombre` = 'San Bernardo', id_region='7' WHERE `ciudades`.`id` = 91;
UPDATE `ciudades` SET `nombre` = 'Alhué', id_region='7' WHERE `ciudades`.`id` = 92;
UPDATE `ciudades` SET `nombre` = 'Curacaví', id_region='7' WHERE `ciudades`.`id` = 93;
UPDATE `ciudades` SET `nombre` = 'María Pinto', id_region='7' WHERE `ciudades`.`id` = 94;
UPDATE `ciudades` SET `nombre` = 'Melipilla', id_region='7' WHERE `ciudades`.`id` = 95;
UPDATE `ciudades` SET `nombre` = 'San Pedro', id_region='7' WHERE `ciudades`.`id` = 96;
UPDATE `ciudades` SET `nombre` = 'Cerrillos', id_region='7' WHERE `ciudades`.`id` = 97;
UPDATE `ciudades` SET `nombre` = 'Cerro Navia', id_region='7' WHERE `ciudades`.`id` = 98;
UPDATE `ciudades` SET `nombre` = 'Conchalí', id_region='7' WHERE `ciudades`.`id` = 99;
UPDATE `ciudades` SET `nombre` = 'El Bosque', id_region='7' WHERE `ciudades`.`id` = 100;
UPDATE `ciudades` SET `nombre` = 'Estación Central', id_region='7' WHERE `ciudades`.`id` = 101;
UPDATE `ciudades` SET `nombre` = 'Huechuraba', id_region='7' WHERE `ciudades`.`id` = 102;
UPDATE `ciudades` SET `nombre` = 'Independencia', id_region='7' WHERE `ciudades`.`id` = 103;
UPDATE `ciudades` SET `nombre` = 'La Cisterna', id_region='7' WHERE `ciudades`.`id` = 104;
UPDATE `ciudades` SET `nombre` = 'La Granja', id_region='7' WHERE `ciudades`.`id` = 105;
UPDATE `ciudades` SET `nombre` = 'La Florida', id_region='7' WHERE `ciudades`.`id` = 106;
UPDATE `ciudades` SET `nombre` = 'La Pintana', id_region='7' WHERE `ciudades`.`id` = 107;
UPDATE `ciudades` SET `nombre` = 'La Reina', id_region='7' WHERE `ciudades`.`id` = 108;
UPDATE `ciudades` SET `nombre` = 'Las Condes', id_region='7' WHERE `ciudades`.`id` = 109;
UPDATE `ciudades` SET `nombre` = 'Lo Barnechea', id_region='7' WHERE `ciudades`.`id` = 110;
UPDATE `ciudades` SET `nombre` = 'Lo Espejo', id_region='7' WHERE `ciudades`.`id` = 111;
UPDATE `ciudades` SET `nombre` = 'Lo Prado', id_region='7' WHERE `ciudades`.`id` = 112;
UPDATE `ciudades` SET `nombre` = 'Macul', id_region='7' WHERE `ciudades`.`id` = 113;
UPDATE `ciudades` SET `nombre` = 'Maipú', id_region='7' WHERE `ciudades`.`id` = 114;
UPDATE `ciudades` SET `nombre` = 'Ñuñoa', id_region='7' WHERE `ciudades`.`id` = 115;
UPDATE `ciudades` SET `nombre` = 'Pedro Aguirre Cerda', id_region='7' WHERE `ciudades`.`id` = 116;
UPDATE `ciudades` SET `nombre` = 'Peñalolén', id_region='7' WHERE `ciudades`.`id` = 117;
UPDATE `ciudades` SET `nombre` = 'Providencia', id_region='7' WHERE `ciudades`.`id` = 118;
UPDATE `ciudades` SET `nombre` = 'Pudahuel', id_region='7' WHERE `ciudades`.`id` = 119;
UPDATE `ciudades` SET `nombre` = 'Quilicura', id_region='7' WHERE `ciudades`.`id` = 120;
UPDATE `ciudades` SET `nombre` = 'Quinta Normal', id_region='7' WHERE `ciudades`.`id` = 121;
UPDATE `ciudades` SET `nombre` = 'Recoleta', id_region='7' WHERE `ciudades`.`id` = 122;
UPDATE `ciudades` SET `nombre` = 'Renca', id_region='7' WHERE `ciudades`.`id` = 123;
UPDATE `ciudades` SET `nombre` = 'San Miguel', id_region='7' WHERE `ciudades`.`id` = 124;
UPDATE `ciudades` SET `nombre` = 'San Joaquín', id_region='7' WHERE `ciudades`.`id` = 125;
UPDATE `ciudades` SET `nombre` = 'San Ramón', id_region='7' WHERE `ciudades`.`id` = 126;
UPDATE `ciudades` SET `nombre` = 'Santiago', id_region='7' WHERE `ciudades`.`id` = 127;
UPDATE `ciudades` SET `nombre` = 'Vitacura', id_region='7' WHERE `ciudades`.`id` = 128;
UPDATE `ciudades` SET `nombre` = 'El Monte', id_region='7' WHERE `ciudades`.`id` = 129;
UPDATE `ciudades` SET `nombre` = 'Isla de Maipo', id_region='7' WHERE `ciudades`.`id` = 130;
UPDATE `ciudades` SET `nombre` = 'Padre Hurtado', id_region='7' WHERE `ciudades`.`id` = 131;
UPDATE `ciudades` SET `nombre` = 'Peñaflor', id_region='7' WHERE `ciudades`.`id` = 132;
UPDATE `ciudades` SET `nombre` = 'Talagante', id_region='7' WHERE `ciudades`.`id` = 133;
UPDATE `ciudades` SET `nombre` = 'Codegua', id_region='8' WHERE `ciudades`.`id` = 134;
UPDATE `ciudades` SET `nombre` = 'Coínco', id_region='8' WHERE `ciudades`.`id` = 135;
UPDATE `ciudades` SET `nombre` = 'Coltauco', id_region='8' WHERE `ciudades`.`id` = 136;
UPDATE `ciudades` SET `nombre` = 'Doñihue', id_region='8' WHERE `ciudades`.`id` = 137;
UPDATE `ciudades` SET `nombre` = 'Graneros', id_region='8' WHERE `ciudades`.`id` = 138;
UPDATE `ciudades` SET `nombre` = 'Las Cabras', id_region='8' WHERE `ciudades`.`id` = 139;
UPDATE `ciudades` SET `nombre` = 'Machalí', id_region='8' WHERE `ciudades`.`id` = 140;
UPDATE `ciudades` SET `nombre` = 'Malloa', id_region='8' WHERE `ciudades`.`id` = 141;
UPDATE `ciudades` SET `nombre` = 'Mostazal', id_region='8' WHERE `ciudades`.`id` = 142;
UPDATE `ciudades` SET `nombre` = 'Olivar', id_region='8' WHERE `ciudades`.`id` = 143;
UPDATE `ciudades` SET `nombre` = 'Peumo', id_region='8' WHERE `ciudades`.`id` = 144;
UPDATE `ciudades` SET `nombre` = 'Pichidegua', id_region='8' WHERE `ciudades`.`id` = 145;
UPDATE `ciudades` SET `nombre` = 'Quinta de Tilcoco', id_region='8' WHERE `ciudades`.`id` = 146;
UPDATE `ciudades` SET `nombre` = 'Rancagua', id_region='8' WHERE `ciudades`.`id` = 147;
UPDATE `ciudades` SET `nombre` = 'Rengo', id_region='8' WHERE `ciudades`.`id` = 148;
UPDATE `ciudades` SET `nombre` = 'Requínoa', id_region='8' WHERE `ciudades`.`id` = 149;
UPDATE `ciudades` SET `nombre` = 'San Vicente de Tagua Tagua', id_region='8' WHERE `ciudades`.`id` = 150;
UPDATE `ciudades` SET `nombre` = 'La Estrella', id_region='8' WHERE `ciudades`.`id` = 151;
UPDATE `ciudades` SET `nombre` = 'Litueche', id_region='8' WHERE `ciudades`.`id` = 152;
UPDATE `ciudades` SET `nombre` = 'Marchihue', id_region='8' WHERE `ciudades`.`id` = 153;
UPDATE `ciudades` SET `nombre` = 'Navidad', id_region='8' WHERE `ciudades`.`id` = 154;
UPDATE `ciudades` SET `nombre` = 'Paredones', id_region='8' WHERE `ciudades`.`id` = 155;
UPDATE `ciudades` SET `nombre` = 'Pichilemu', id_region='8' WHERE `ciudades`.`id` = 156;
UPDATE `ciudades` SET `nombre` = 'Chépica', id_region='8' WHERE `ciudades`.`id` = 157;
UPDATE `ciudades` SET `nombre` = 'Chimbarongo', id_region='8' WHERE `ciudades`.`id` = 158;
UPDATE `ciudades` SET `nombre` = 'Lolol', id_region='8' WHERE `ciudades`.`id` = 159;
UPDATE `ciudades` SET `nombre` = 'Nancagua', id_region='8' WHERE `ciudades`.`id` = 160;
UPDATE `ciudades` SET `nombre` = 'Palmilla', id_region='8' WHERE `ciudades`.`id` = 161;
UPDATE `ciudades` SET `nombre` = 'Peralillo', id_region='8' WHERE `ciudades`.`id` = 162;
UPDATE `ciudades` SET `nombre` = 'Placilla', id_region='8' WHERE `ciudades`.`id` = 163;
UPDATE `ciudades` SET `nombre` = 'Pumanque', id_region='8' WHERE `ciudades`.`id` = 164;
UPDATE `ciudades` SET `nombre` = 'San Fernando', id_region='8' WHERE `ciudades`.`id` = 165;
UPDATE `ciudades` SET `nombre` = 'Santa Cruz', id_region='8' WHERE `ciudades`.`id` = 166;
UPDATE `ciudades` SET `nombre` = 'Cauquenes', id_region='9' WHERE `ciudades`.`id` = 167;
UPDATE `ciudades` SET `nombre` = 'Chanco', id_region='9' WHERE `ciudades`.`id` = 168;
UPDATE `ciudades` SET `nombre` = 'Pelluhue', id_region='9' WHERE `ciudades`.`id` = 169;
UPDATE `ciudades` SET `nombre` = 'Curicó', id_region='9' WHERE `ciudades`.`id` = 170;
UPDATE `ciudades` SET `nombre` = 'Hualañé', id_region='9' WHERE `ciudades`.`id` = 171;
UPDATE `ciudades` SET `nombre` = 'Licantén', id_region='9' WHERE `ciudades`.`id` = 172;
UPDATE `ciudades` SET `nombre` = 'Molina', id_region='9' WHERE `ciudades`.`id` = 173;
UPDATE `ciudades` SET `nombre` = 'Rauco', id_region='9' WHERE `ciudades`.`id` = 174;
UPDATE `ciudades` SET `nombre` = 'Romeral', id_region='9' WHERE `ciudades`.`id` = 175;
UPDATE `ciudades` SET `nombre` = 'Sagrada Familia', id_region='9' WHERE `ciudades`.`id` = 176;
UPDATE `ciudades` SET `nombre` = 'Teno', id_region='9' WHERE `ciudades`.`id` = 177;
UPDATE `ciudades` SET `nombre` = 'Vichuquén', id_region='9' WHERE `ciudades`.`id` = 178;
UPDATE `ciudades` SET `nombre` = 'Colbún', id_region='9' WHERE `ciudades`.`id` = 179;
UPDATE `ciudades` SET `nombre` = 'Linares', id_region='9' WHERE `ciudades`.`id` = 180;
UPDATE `ciudades` SET `nombre` = 'Longaví', id_region='9' WHERE `ciudades`.`id` = 181;
UPDATE `ciudades` SET `nombre` = 'Parral', id_region='9' WHERE `ciudades`.`id` = 182;
UPDATE `ciudades` SET `nombre` = 'Retiro', id_region='9' WHERE `ciudades`.`id` = 183;
UPDATE `ciudades` SET `nombre` = 'San Javier', id_region='9' WHERE `ciudades`.`id` = 184;
UPDATE `ciudades` SET `nombre` = 'Villa Alegre', id_region='9' WHERE `ciudades`.`id` = 185;
UPDATE `ciudades` SET `nombre` = 'Yerbas Buenas', id_region='9' WHERE `ciudades`.`id` = 186;
UPDATE `ciudades` SET `nombre` = 'Constitución', id_region='9' WHERE `ciudades`.`id` = 187;
UPDATE `ciudades` SET `nombre` = 'Curepto', id_region='9' WHERE `ciudades`.`id` = 188;
UPDATE `ciudades` SET `nombre` = 'Empedrado', id_region='9' WHERE `ciudades`.`id` = 189;
UPDATE `ciudades` SET `nombre` = 'Maule', id_region='9' WHERE `ciudades`.`id` = 190;
UPDATE `ciudades` SET `nombre` = 'Pelarco', id_region='9' WHERE `ciudades`.`id` = 191;
UPDATE `ciudades` SET `nombre` = 'Pencahue', id_region='9' WHERE `ciudades`.`id` = 192;
UPDATE `ciudades` SET `nombre` = 'Río Claro', id_region='9' WHERE `ciudades`.`id` = 193;
UPDATE `ciudades` SET `nombre` = 'San Clemente', id_region='9' WHERE `ciudades`.`id` = 194;
UPDATE `ciudades` SET `nombre` = 'San Rafael', id_region='9' WHERE `ciudades`.`id` = 195;
UPDATE `ciudades` SET `nombre` = 'Talca', id_region='9' WHERE `ciudades`.`id` = 196;
UPDATE `ciudades` SET `nombre` = 'Arauco', id_region='11' WHERE `ciudades`.`id` = 197;
UPDATE `ciudades` SET `nombre` = 'Cañete', id_region='11' WHERE `ciudades`.`id` = 198;
UPDATE `ciudades` SET `nombre` = 'Contulmo', id_region='11' WHERE `ciudades`.`id` = 199;
UPDATE `ciudades` SET `nombre` = 'Curanilahue', id_region='11' WHERE `ciudades`.`id` = 200;
UPDATE `ciudades` SET `nombre` = 'Lebu', id_region='11' WHERE `ciudades`.`id` = 201;
UPDATE `ciudades` SET `nombre` = 'Los Álamos', id_region='11' WHERE `ciudades`.`id` = 202;
UPDATE `ciudades` SET `nombre` = 'Tirúa', id_region='11' WHERE `ciudades`.`id` = 203;
UPDATE `ciudades` SET `nombre` = 'Alto Biobío', id_region='11' WHERE `ciudades`.`id` = 204;
UPDATE `ciudades` SET `nombre` = 'Antuco', id_region='11' WHERE `ciudades`.`id` = 205;
UPDATE `ciudades` SET `nombre` = 'Cabrero', id_region='11' WHERE `ciudades`.`id` = 206;
UPDATE `ciudades` SET `nombre` = 'Laja', id_region='11' WHERE `ciudades`.`id` = 207;
UPDATE `ciudades` SET `nombre` = 'Los Ángeles', id_region='11' WHERE `ciudades`.`id` = 208;
UPDATE `ciudades` SET `nombre` = 'Mulchén', id_region='11' WHERE `ciudades`.`id` = 209;
UPDATE `ciudades` SET `nombre` = 'Nacimiento', id_region='11' WHERE `ciudades`.`id` = 210;
UPDATE `ciudades` SET `nombre` = 'Negrete', id_region='11' WHERE `ciudades`.`id` = 211;
UPDATE `ciudades` SET `nombre` = 'Quilaco', id_region='11' WHERE `ciudades`.`id` = 212;
UPDATE `ciudades` SET `nombre` = 'Quilleco', id_region='11' WHERE `ciudades`.`id` = 213;
UPDATE `ciudades` SET `nombre` = 'San Rosendo', id_region='11' WHERE `ciudades`.`id` = 214;
UPDATE `ciudades` SET `nombre` = 'Santa Bárbara', id_region='11' WHERE `ciudades`.`id` = 215;
UPDATE `ciudades` SET `nombre` = 'Tucapel', id_region='11' WHERE `ciudades`.`id` = 216;
UPDATE `ciudades` SET `nombre` = 'Yumbel', id_region='11' WHERE `ciudades`.`id` = 217;
UPDATE `ciudades` SET `nombre` = 'Chiguayante', id_region='11' WHERE `ciudades`.`id` = 218;
UPDATE `ciudades` SET `nombre` = 'Concepción', id_region='11' WHERE `ciudades`.`id` = 219;
UPDATE `ciudades` SET `nombre` = 'Coronel', id_region='11' WHERE `ciudades`.`id` = 220;
UPDATE `ciudades` SET `nombre` = 'Florida', id_region='11' WHERE `ciudades`.`id` = 221;
UPDATE `ciudades` SET `nombre` = 'Hualpén', id_region='11' WHERE `ciudades`.`id` = 222;
UPDATE `ciudades` SET `nombre` = 'Hualqui', id_region='11' WHERE `ciudades`.`id` = 223;
UPDATE `ciudades` SET `nombre` = 'Lota', id_region='11' WHERE `ciudades`.`id` = 224;
UPDATE `ciudades` SET `nombre` = 'Penco', id_region='11' WHERE `ciudades`.`id` = 225;
UPDATE `ciudades` SET `nombre` = 'San Pedro de La Paz', id_region='11' WHERE `ciudades`.`id` = 226;
UPDATE `ciudades` SET `nombre` = 'Santa Juana', id_region='11' WHERE `ciudades`.`id` = 227;
UPDATE `ciudades` SET `nombre` = 'Talcahuano', id_region='11' WHERE `ciudades`.`id` = 228;
UPDATE `ciudades` SET `nombre` = 'Tomé', id_region='11' WHERE `ciudades`.`id` = 229;
UPDATE `ciudades` SET `nombre` = 'Bulnes', id_region='10' WHERE `ciudades`.`id` = 230;
UPDATE `ciudades` SET `nombre` = 'Chillán', id_region='10' WHERE `ciudades`.`id` = 231;
UPDATE `ciudades` SET `nombre` = 'Chillán Viejo', id_region='10' WHERE `ciudades`.`id` = 232;
UPDATE `ciudades` SET `nombre` = 'Cobquecura', id_region='10' WHERE `ciudades`.`id` = 233;
UPDATE `ciudades` SET `nombre` = 'Coelemu', id_region='10' WHERE `ciudades`.`id` = 234;
UPDATE `ciudades` SET `nombre` = 'Coihueco', id_region='10' WHERE `ciudades`.`id` = 235;
UPDATE `ciudades` SET `nombre` = 'El Carmen', id_region='10' WHERE `ciudades`.`id` = 236;
UPDATE `ciudades` SET `nombre` = 'Ninhue', id_region='10' WHERE `ciudades`.`id` = 237;
UPDATE `ciudades` SET `nombre` = 'Ñiquen', id_region='10' WHERE `ciudades`.`id` = 238;
UPDATE `ciudades` SET `nombre` = 'Pemuco', id_region='10' WHERE `ciudades`.`id` = 239;
UPDATE `ciudades` SET `nombre` = 'Pinto', id_region='10' WHERE `ciudades`.`id` = 240;
UPDATE `ciudades` SET `nombre` = 'Portezuelo', id_region='10' WHERE `ciudades`.`id` = 241;
UPDATE `ciudades` SET `nombre` = 'Quillón', id_region='10' WHERE `ciudades`.`id` = 242;
UPDATE `ciudades` SET `nombre` = 'Quirihue', id_region='10' WHERE `ciudades`.`id` = 243;
UPDATE `ciudades` SET `nombre` = 'Ránquil', id_region='10' WHERE `ciudades`.`id` = 244;
UPDATE `ciudades` SET `nombre` = 'San Carlos', id_region='10' WHERE `ciudades`.`id` = 245;
UPDATE `ciudades` SET `nombre` = 'San Fabián', id_region='10' WHERE `ciudades`.`id` = 246;
UPDATE `ciudades` SET `nombre` = 'San Ignacio', id_region='10' WHERE `ciudades`.`id` = 247;
UPDATE `ciudades` SET `nombre` = 'San Nicolás', id_region='10' WHERE `ciudades`.`id` = 248;
UPDATE `ciudades` SET `nombre` = 'Treguaco', id_region='10' WHERE `ciudades`.`id` = 249;
UPDATE `ciudades` SET `nombre` = 'Yungay', id_region='10' WHERE `ciudades`.`id` = 250;
UPDATE `ciudades` SET `nombre` = 'Carahue', id_region='12' WHERE `ciudades`.`id` = 251;
UPDATE `ciudades` SET `nombre` = 'Cholchol', id_region='12' WHERE `ciudades`.`id` = 252;
UPDATE `ciudades` SET `nombre` = 'Cunco', id_region='12' WHERE `ciudades`.`id` = 253;
UPDATE `ciudades` SET `nombre` = 'Curarrehue', id_region='12' WHERE `ciudades`.`id` = 254;
UPDATE `ciudades` SET `nombre` = 'Freire', id_region='12' WHERE `ciudades`.`id` = 255;
UPDATE `ciudades` SET `nombre` = 'Galvarino', id_region='12' WHERE `ciudades`.`id` = 256;
UPDATE `ciudades` SET `nombre` = 'Gorbea', id_region='12' WHERE `ciudades`.`id` = 257;
UPDATE `ciudades` SET `nombre` = 'Lautaro', id_region='12' WHERE `ciudades`.`id` = 258;
UPDATE `ciudades` SET `nombre` = 'Loncoche', id_region='12' WHERE `ciudades`.`id` = 259;
UPDATE `ciudades` SET `nombre` = 'Melipeuco', id_region='12' WHERE `ciudades`.`id` = 260;
UPDATE `ciudades` SET `nombre` = 'Nueva Imperial', id_region='12' WHERE `ciudades`.`id` = 261;
UPDATE `ciudades` SET `nombre` = 'Padre Las Casas', id_region='12' WHERE `ciudades`.`id` = 262;
UPDATE `ciudades` SET `nombre` = 'Perquenco', id_region='12' WHERE `ciudades`.`id` = 263;
UPDATE `ciudades` SET `nombre` = 'Pitrufquén', id_region='12' WHERE `ciudades`.`id` = 264;
UPDATE `ciudades` SET `nombre` = 'Pucón', id_region='12' WHERE `ciudades`.`id` = 265;
UPDATE `ciudades` SET `nombre` = 'Saavedra', id_region='12' WHERE `ciudades`.`id` = 266;
UPDATE `ciudades` SET `nombre` = 'Temuco', id_region='12' WHERE `ciudades`.`id` = 267;
UPDATE `ciudades` SET `nombre` = 'Teodoro Schmidt', id_region='12' WHERE `ciudades`.`id` = 268;
UPDATE `ciudades` SET `nombre` = 'Toltén', id_region='12' WHERE `ciudades`.`id` = 269;
UPDATE `ciudades` SET `nombre` = 'Vilcún', id_region='12' WHERE `ciudades`.`id` = 270;
UPDATE `ciudades` SET `nombre` = 'Villarrica', id_region='12' WHERE `ciudades`.`id` = 271;
UPDATE `ciudades` SET `nombre` = 'Angol', id_region='12' WHERE `ciudades`.`id` = 272;
UPDATE `ciudades` SET `nombre` = 'Collipulli', id_region='12' WHERE `ciudades`.`id` = 273;
UPDATE `ciudades` SET `nombre` = 'Curacautín', id_region='12' WHERE `ciudades`.`id` = 274;
UPDATE `ciudades` SET `nombre` = 'Ercilla', id_region='12' WHERE `ciudades`.`id` = 275;
UPDATE `ciudades` SET `nombre` = 'Lonquimay', id_region='12' WHERE `ciudades`.`id` = 276;
UPDATE `ciudades` SET `nombre` = 'Los Sauces', id_region='12' WHERE `ciudades`.`id` = 277;
UPDATE `ciudades` SET `nombre` = 'Lumaco', id_region='12' WHERE `ciudades`.`id` = 278;
UPDATE `ciudades` SET `nombre` = 'Purén', id_region='12' WHERE `ciudades`.`id` = 279;
UPDATE `ciudades` SET `nombre` = 'Renaico', id_region='12' WHERE `ciudades`.`id` = 280;
UPDATE `ciudades` SET `nombre` = 'Traiguén', id_region='12' WHERE `ciudades`.`id` = 281;
UPDATE `ciudades` SET `nombre` = 'Victoria', id_region='12' WHERE `ciudades`.`id` = 282;
UPDATE `ciudades` SET `nombre` = 'Corral', id_region='13' WHERE `ciudades`.`id` = 283;
UPDATE `ciudades` SET `nombre` = 'Lanco', id_region='13' WHERE `ciudades`.`id` = 284;
UPDATE `ciudades` SET `nombre` = 'Los Lagos', id_region='13' WHERE `ciudades`.`id` = 285;
UPDATE `ciudades` SET `nombre` = 'Máfil', id_region='13' WHERE `ciudades`.`id` = 286;
UPDATE `ciudades` SET `nombre` = 'Mariquina', id_region='13' WHERE `ciudades`.`id` = 287;
UPDATE `ciudades` SET `nombre` = 'Paillaco', id_region='13' WHERE `ciudades`.`id` = 288;
UPDATE `ciudades` SET `nombre` = 'Panguipulli', id_region='13' WHERE `ciudades`.`id` = 289;
UPDATE `ciudades` SET `nombre` = 'Valdivia', id_region='13' WHERE `ciudades`.`id` = 290;
UPDATE `ciudades` SET `nombre` = 'Futrono', id_region='13' WHERE `ciudades`.`id` = 291;
UPDATE `ciudades` SET `nombre` = 'La Unión', id_region='13' WHERE `ciudades`.`id` = 292;
UPDATE `ciudades` SET `nombre` = 'Lago Ranco', id_region='13' WHERE `ciudades`.`id` = 293;
UPDATE `ciudades` SET `nombre` = 'Río Bueno', id_region='13' WHERE `ciudades`.`id` = 294;
UPDATE `ciudades` SET `nombre` = 'Ancud', id_region='14' WHERE `ciudades`.`id` = 295;
UPDATE `ciudades` SET `nombre` = 'Castro', id_region='14' WHERE `ciudades`.`id` = 296;
UPDATE `ciudades` SET `nombre` = 'Chonchi', id_region='14' WHERE `ciudades`.`id` = 297;
UPDATE `ciudades` SET `nombre` = 'Curaco de Vélez', id_region='14' WHERE `ciudades`.`id` = 298;
UPDATE `ciudades` SET `nombre` = 'Dalcahue', id_region='14' WHERE `ciudades`.`id` = 299;
UPDATE `ciudades` SET `nombre` = 'Puqueldón', id_region='14' WHERE `ciudades`.`id` = 300;
UPDATE `ciudades` SET `nombre` = 'Queilén', id_region='14' WHERE `ciudades`.`id` = 301;
UPDATE `ciudades` SET `nombre` = 'Quemchi', id_region='14' WHERE `ciudades`.`id` = 302;
UPDATE `ciudades` SET `nombre` = 'Quellón', id_region='14' WHERE `ciudades`.`id` = 303;
UPDATE `ciudades` SET `nombre` = 'Quinchao', id_region='14' WHERE `ciudades`.`id` = 304;
UPDATE `ciudades` SET `nombre` = 'Calbuco', id_region='14' WHERE `ciudades`.`id` = 305;
UPDATE `ciudades` SET `nombre` = 'Cochamó', id_region='14' WHERE `ciudades`.`id` = 306;
UPDATE `ciudades` SET `nombre` = 'Fresia', id_region='14' WHERE `ciudades`.`id` = 307;
UPDATE `ciudades` SET `nombre` = 'Frutillar', id_region='14' WHERE `ciudades`.`id` = 308;
UPDATE `ciudades` SET `nombre` = 'Llanquihue', id_region='14' WHERE `ciudades`.`id` = 309;
UPDATE `ciudades` SET `nombre` = 'Los Muermos', id_region='14' WHERE `ciudades`.`id` = 310;
UPDATE `ciudades` SET `nombre` = 'Maullín', id_region='14' WHERE `ciudades`.`id` = 311;
UPDATE `ciudades` SET `nombre` = 'Puerto Montt', id_region='14' WHERE `ciudades`.`id` = 312;
UPDATE `ciudades` SET `nombre` = 'Puerto Varas', id_region='14' WHERE `ciudades`.`id` = 313;
UPDATE `ciudades` SET `nombre` = 'Osorno', id_region='14' WHERE `ciudades`.`id` = 314;
UPDATE `ciudades` SET `nombre` = 'Puero Octay', id_region='14' WHERE `ciudades`.`id` = 315;
UPDATE `ciudades` SET `nombre` = 'Purranque', id_region='14' WHERE `ciudades`.`id` = 316;
UPDATE `ciudades` SET `nombre` = 'Puyehue', id_region='14' WHERE `ciudades`.`id` = 317;
UPDATE `ciudades` SET `nombre` = 'Río Negro', id_region='14' WHERE `ciudades`.`id` = 318;
UPDATE `ciudades` SET `nombre` = 'San Juan de la Costa', id_region='14' WHERE `ciudades`.`id` = 319;
UPDATE `ciudades` SET `nombre` = 'San Pablo', id_region='14' WHERE `ciudades`.`id` = 320;
UPDATE `ciudades` SET `nombre` = 'Chaitén', id_region='14' WHERE `ciudades`.`id` = 321;
UPDATE `ciudades` SET `nombre` = 'Futaleufú', id_region='14' WHERE `ciudades`.`id` = 322;
UPDATE `ciudades` SET `nombre` = 'Hualaihué', id_region='14' WHERE `ciudades`.`id` = 323;
UPDATE `ciudades` SET `nombre` = 'Palena', id_region='14' WHERE `ciudades`.`id` = 324;
UPDATE `ciudades` SET `nombre` = 'Aisén', id_region='15' WHERE `ciudades`.`id` = 325;
UPDATE `ciudades` SET `nombre` = 'Cisnes', id_region='15' WHERE `ciudades`.`id` = 326;
UPDATE `ciudades` SET `nombre` = 'Guaitecas', id_region='15' WHERE `ciudades`.`id` = 327;
UPDATE `ciudades` SET `nombre` = 'Cochrane', id_region='15' WHERE `ciudades`.`id` = 328;
UPDATE `ciudades` SET `nombre` = 'O\'higgins', id_region='15' WHERE `ciudades`.`id` = 329;
UPDATE `ciudades` SET `nombre` = 'Tortel', id_region='15' WHERE `ciudades`.`id` = 330;
UPDATE `ciudades` SET `nombre` = 'Coihaique', id_region='15' WHERE `ciudades`.`id` = 331;
UPDATE `ciudades` SET `nombre` = 'Lago Verde', id_region='15' WHERE `ciudades`.`id` = 332;
UPDATE `ciudades` SET `nombre` = 'Chile Chico', id_region='15' WHERE `ciudades`.`id` = 333;
UPDATE `ciudades` SET `nombre` = 'Río Ibáñez', id_region='15' WHERE `ciudades`.`id` = 334;
UPDATE `ciudades` SET `nombre` = 'Antártica', id_region='16' WHERE `ciudades`.`id` = 335;
UPDATE `ciudades` SET `nombre` = 'Cabo de Hornos', id_region='16' WHERE `ciudades`.`id` = 336;
UPDATE `ciudades` SET `nombre` = 'Laguna Blanca', id_region='16' WHERE `ciudades`.`id` = 337;
UPDATE `ciudades` SET `nombre` = 'Punta Arenas', id_region='16' WHERE `ciudades`.`id` = 338;
UPDATE `ciudades` SET `nombre` = 'Río Verde', id_region='16' WHERE `ciudades`.`id` = 339;
UPDATE `ciudades` SET `nombre` = 'San Gregorio', id_region='16' WHERE `ciudades`.`id` = 340;
UPDATE `ciudades` SET `nombre` = 'Porvenir', id_region='16' WHERE `ciudades`.`id` = 341;
UPDATE `ciudades` SET `nombre` = 'Primavera', id_region='16' WHERE `ciudades`.`id` = 342;
UPDATE `ciudades` SET `nombre` = 'Timaukel', id_region='16' WHERE `ciudades`.`id` = 343;
UPDATE `ciudades` SET `nombre` = 'Natales', id_region='16' WHERE `ciudades`.`id` = 344;
UPDATE `ciudades` SET `nombre` = 'Torres del Paine', id_region='16' WHERE `ciudades`.`id` = 345;
UPDATE `ciudades` SET `nombre` = 'Cabildo', id_region='6' WHERE `ciudades`.`id` = 346;
